language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

install:
  - dotnet tool install -g coveralls.net --version 1.0.0
  - dotnet restore

script:
  - dotnet build
 # - dotnet test TravisExemplo.Test.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=".coverage/coverage.opencover.xml"  -p:Exclude="[TravisExemplo.Tests*]*" -p:Exclude="[xunit*]*"
 