language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

install:
  - dotnet tool install -g coveralls.net --version 1.0.0
  - dotnet restore

script:
  - dotnet build
  - dotnet test Test/TravisExemplo.Tests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=".coverage/coverage.opencover.xml"  -p:Exclude="[TravisExemplo.Tests*]*" -p:Exclude="[xunit*]*"
  - $HOME/.dotnet/tools/csmacnz.Coveralls -i TravisExemplo.Tests/.coverage/coverage.opencover.xml --opencover --repoToken $COVERALLS_REPO_TOKEN --jobId $TRAVIS_JOB_ID --serviceName "travis-ci" --useRelativePaths